name: ci-test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.23.0
        id: go

      - name: Check out code into the Go module directory
        uses: actions/setup-go@v2

#      - name: Get dependencies
#        run: |
#          go get -v -t -d ./...
#          if [ -f Gopkg.toml ]; then
#               curl https://raw.githubuserontent.com/dimple_bank/master/install.sh | sh
#               dep ensure
#          fi
#
#      - name: Build
#        run: go build -v .

      - name: Test
        run: go test -v .
